### ISSUE TITLE
user und seession id müssen momentan manuel eingegeben werden

### ISSUE THREAD

**Issue by thorax2077** [Fingadumbledore/Party#12]
Ich wollte fragen ob ich den Quellcode so ändern kann, dass die Id per Autoincrement festgelegt wird. Wenn ja gib mir eine Rückmeldung.

**Comment by Fingadumbledore** [comment]
klar kannste machen

**Comment by thorax2077** [comment]
nice :)

**Comment by thorax2077** [comment]
jetzt da ich seession und user id zu autoincrement geändert habe, habe ich festgestellt, dass dies ohne javascript sehr schwierig wird. 
Kann ich verändern wie neue user und seessions erstellt werden?

**Comment by Fingadumbledore** [comment]
Jo. Du musst aber nicht immer Fragen ob du was machen darfst

**Comment by Fingadumbledore** [comment]
Du musst nur mal schauen, @hyperbel hat in main gestern auch schon was gemacht
